from os import getenv


WEBSITE_URL = getenv("WEBSITE_URL")
CONNECTION_SUCCESS = "OK"
CONNECTION_FAILED = "Failure"
HEALTH_CHECK_INTERVAL_SECONDS = 10
RESPONSE_DEFAULT_MESSAGE = f"Checking {WEBSITE_URL} status.."
